// tools/coverage-scan.mjs — full-pack ground-truth scan.
//
// Classifies every file in a pack three ways:
//   xmp  — does C libxmp load it?          (probe-xmp)
//   ompt — does C libopenmpt load it?      (probe-ompt)
//   ours — does our TS plugin set load it? (xmpdump.mjs bundle)
//
// Usage: node tools/coverage-scan.mjs <pack-dir> [--out report.md] [--filter ext]
// Probes must exist: /tmp/probe-xmp /tmp/probe-ompt (built from /tmp/opencode/*.c).

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, relative, extname } from 'node:path';

const repo = new URL('..', import.meta.url).pathname;
const packDir = process.argv[2];
if (!packDir) {
  console.error('usage: tools/coverage-scan.mjs <pack-dir>');
  process.exit(2);
}
const opt = (name, def) => {
  const i = process.argv.indexOf('--' + name);
  return i >= 0 && process.argv[i + 1] !== undefined ? process.argv[i + 1] : def;
};
const outFile = opt('out', 'out/coverage-report.md');
const filter = opt('filter', null);

// ---- walk -------------------------------------------------------------------

function walk(dir) {
  const files = [];
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    const st = statSync(p);
    if (st.isDirectory()) files.push(...walk(p));
    else files.push(p);
  }
  return files;
}

const allFiles = walk(packDir).sort();
const files = filter ? allFiles.filter(f => extname(f).toLowerCase() === '.' + filter) : allFiles;
console.error(`scanning ${files.length} files...`);

// ---- our loader bundle -------------------------------------------------------

const esbuild = (await import('esbuild')).default;
const aliasMap = Object.fromEntries(
  ['core', 'effects-shared', 'fmt-mod', 'fmt-s3m', 'fmt-xm', 'fmt-it', 'fmt-mtm', 'fmt-stm', 'fmt-669', 'fmt-sfx', 'fmt-digi', 'fmt-asylum', 'fmt-ice', 'fmt-prowizard', 'fmt-med']
    .map(p => [`@modplayjs/${p}`, join(repo, `packages/${p}/src/index.ts`)]));
const bundle = join(repo, 'out/coverage-bundle.mjs');
await esbuild.build({
  entryPoints: [join(repo, 'tools/xmpdump-entry.mjs')],
  bundle: true, platform: 'node', format: 'esm',
  alias: aliasMap, outfile: bundle, logLevel: 'silent',
});
const { CorePlayer, modPlugin, hmnPlugin, fltPlugin, pwPlugin, s3mPlugin, xmPlugin, itPlugin, mtmPlugin, stmPlugin, s69Plugin, sfxPlugin, digiPlugin, asylumPlugin, icePlugin, medPlugin, mmd3Plugin, med2Plugin, med3Plugin, med4Plugin } = await import(
  'file://' + bundle);
const core = new CorePlayer();
core.registries.registerFormat(modPlugin);
core.registries.registerFormat(hmnPlugin);
core.registries.registerFormat(fltPlugin);
core.registries.registerFormat(pwPlugin);
core.registries.registerFormat(s3mPlugin);
core.registries.registerFormat(xmPlugin);
core.registries.registerFormat(itPlugin);
core.registries.registerFormat(mtmPlugin);
core.registries.registerFormat(stmPlugin);
core.registries.registerFormat(s69Plugin);
core.registries.registerFormat(sfxPlugin);
core.registries.registerFormat(digiPlugin);
core.registries.registerFormat(asylumPlugin);
core.registries.registerFormat(icePlugin);
core.registries.registerFormat(medPlugin);
core.registries.registerFormat(mmd3Plugin);
core.registries.registerFormat(med2Plugin);
core.registries.registerFormat(med3Plugin);
core.registries.registerFormat(med4Plugin);

function oursLoad(file) {
  try {
    const bytes = new Uint8Array(readFileSync(file));
    core.loadModule(bytes, {});
    const mod = core.module;
    const dur = mod ? `${mod.len}ord` : '';
    core.destroy();
    return { ok: true, note: dur };
  } catch (e) {
    try { core.destroy(); } catch {}
    return { ok: false, note: String(e.message || e).slice(0, 80) };
  }
}

// ---- scan --------------------------------------------------------------------

const rows = [];
for (const f of files) {
  const rel = relative(packDir, f);
  const ext = extname(f).toLowerCase().slice(1);
  let xmp = false, ompt = false;
  try { execFileSync('/tmp/probe-xmp', [f], { timeout: 15000, stdio: 'pipe' }); xmp = true; } catch {}
  try { execFileSync('/tmp/probe-ompt', [f], { timeout: 15000, stdio: 'pipe' }); ompt = true; } catch {}
  const ours = oursLoad(f);
  rows.push({ rel, ext, xmp, ompt, ours: ours.ok, note: ours.note });
  process.stderr.write(`\r${rows.length}/${files.length}`);
}
process.stderr.write('\n');

// ---- report ------------------------------------------------------------------

const byExt = new Map();
for (const r of rows) {
  if (!byExt.has(r.ext)) byExt.set(r.ext, []);
  byExt.get(r.ext).push(r);
}
const lines = [];
lines.push('# Coverage report — ' + packDir);
lines.push('');
lines.push(`Files scanned: ${rows.length} — generated by tools/coverage-scan.mjs`);
lines.push('');
lines.push('| ext | total | libxmp | openmpt | ref-any | ours |');
lines.push('|---|---|---|---|---|---|');
const sorted = [...byExt.entries()].sort((a, b) => b[1].length - a[1].length);
for (const [ext, rs] of sorted) {
  const x = rs.filter(r => r.xmp).length;
  const o = rs.filter(r => r.ompt).length;
  const any = rs.filter(r => r.xmp || r.ompt).length;
  const u = rs.filter(r => r.ours).length;
  lines.push(`| ${ext || '(none)'} | ${rs.length} | ${x} | ${o} | ${any} | ${u} |`);
}
lines.push('');
lines.push('## In-scope load failures (ref loads it, ours does not)');
lines.push('');
for (const [ext, rs] of sorted) {
  const bad = rs.filter(r => (r.xmp || r.ompt) && !r.ours);
  if (!bad.length) continue;
  lines.push(`### .${ext} — ${bad.length} failures`);
  lines.push('');
  for (const r of bad.slice(0, 200)) {
    lines.push(`- [ ] ${r.rel} — xmp:${r.xmp ? 'OK' : 'fail'} ompt:${r.ompt ? 'OK' : 'fail'} — ${r.note}`);
  }
  lines.push('');
}
lines.push('## Out-of-scope formats (no reference parser)');
lines.push('');
for (const [ext, rs] of sorted) {
  if (rs.every(r => !r.xmp && !r.ompt)) {
    lines.push(`- .${ext}: ${rs.length} files — ignored per plan`);
  }
}
lines.push('');

writeFileSync(join(repo, outFile), lines.join('\n'));
console.error(`wrote ${outFile}`);
